version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://root:password123@db:3306/factor_app?serverVersion=mariadb-10.6.18&charset=utf8mb4
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: factor_app
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
