name: Symfony CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo, pdo_mysql, redis
          ini-values: date.timezone=UTC
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Set up .env
        run: |
          cp .env .env.test

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Check code quality (optional)
        run: composer lint

      - name: Build Docker image (optional)
        run: docker build -t symfony_app .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to server
        run: |
          # Deploy script to deploy your application, e.g. via SSH
          echo "Deployment script here"
